name: GPR authentication for npm
description:
  Authenticate npm for consuming and publishing packages from and to the GitHub
  Package Registry on Linux, Windows, and macOS.
author: aquacash5
branding:
  icon: package
  color: gray-dark
inputs:
  token:
    description:
      The token used for authentication. Usually, this should be your
      `secrets.GITHUB_TOKEN`
    required: true
runs:
  using: node12
  main: dist/index.js
